title: Minna Amin
description: UI/UX Designer
site_title: "Minna Amin"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: minna-amin
blog_url: https://minna-amin.github.io
email: minna.amin@gmail.com
#keybase_username: abhn
#twitter_username: abhn_
#reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:
